require 'coveralls'
Coveralls.wear!

URL = 'http://answers.livefyre.com/RUBY'

begin
  NETWORK_NAME = ENV['NETWORK_NAME']
  NETWORK_KEY = ENV['NETWORK_KEY']
  SITE_ID = ENV['SITE_ID']
  SITE_KEY = ENV['SITE_KEY']
  COLLECTION_ID = ENV['COLLECTION_ID']
  USER_ID = ENV['USER_ID']
  ARTICLE_ID = ENV['ARTICLE_ID']
rescue
  NETWORK_NAME = '<NETWORK-NAME>'
  NETWORK_KEY = '<NETWORK-KEY>'
  SITE_ID = '<SITE-ID>'
  SITE_KEY = '<SITE-KEY>'
  COLLECTION_ID = '<COLLECTION-ID>'
  USER_ID = '<USER-ID>'
  ARTICLE_ID = '<ARTICLE-ID>'
end